name: PHP CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with: 
          php-version: '8.2'
      
      - name: Install dependencies
        run: composer install

      - name: Run PHPStan for check static code.
        run: composer run phpstan

      - name: Run tests
        run: composer run phpunit